name: CI

on: [push]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-20.04

    steps:
      - name: Install packages
        run: |
          sudo apt-get -y install wget rsync cpio gzip bzip2 tar unzip make gcc g++ libncurses5-dev build-essential
          
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Update submodules
        run: git submodule update --init
        
      - name: Compile
        run: |
          cd ./buildroot
          make BR2_EXTERNAL=../ somlabs_visionsom_imx6ull_defconfig
          make
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sdcard.img
          path: buildroot/output/images/sdcard.img
       
